//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiEquipmentRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class HisroryOrders
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public int OrderId { get; set; }
        public int Count { get; set; }
        public int Summ { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
